module.exports = {
  general: {
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    loading: '⏳',
    arrow: '➡️',
    back: '⬅️',
    close: '❌',
    check: '✔️',
    cross: '✖️',
    star: '⭐',
  },
  moderation: {
    ban: '🔨',
    kick: '👢',
    mute: '🔇',
    unmute: '🔊',
    warn: '⚠️',
    warnings: '📋',
    purge: '🗑️',
    slowmode: '🐢',
    lock: '🔒',
    unlock: '🔓',
    nickname: '📝',
    timeout: '⏱️',
  },
  utility: {
    ping: '🏓',
    user: '👤',
    server: '🏠',
    time: '⏰',
    help: '❓',
    bot: '🤖',
    stats: '📊',
    setlog: '📝',
    embedbuilder: '🎨',
  },
  fun: {
    smile: '😄',
    party: '🎉',
    say: '💬',
  },
  logs: {
    moderation: '🛡️',
    messages: '💬',
    members: '👥',
    channels: '📢',
    roles: '🎭',
    voice: '🔊',
    server: '🏠',
  },
  embed: {
    star: '⭐',
    chart: '📊',
    refresh: '🔄',
    title: '📌',
    text: '📄',
    separator: '➖',
    thumbnail: '🔳',
    image: '🖼️',
    author: '👤',
    field: '📋',
    section: '✨',
    footer: '📎',
    link: '🔗',
    role: '🎭',
    blocks: '🧱',
    style: '🎨',
    history: '📜',
    export: '💾',
    import: '📥',
    manage: '🔧',
    send: '📤',
    edit: '✏️',
    reset: '🗑️',
    home: '🏠',
  },
};
